---
- name: Update apt cache and upgrade packages on jammy
  hosts: jammy
  become: true
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all apt packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Install necessary packages on jammy
      ansible.builtin.apt:
        name: 
          - vim
          - curl
        state: present

